import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
 const Card = (props) => {
  return (
    <div className={styles.cardContainer}>
        <div className={styles.cardTitle}>
          <h3>{props.title}</h3>
          <p>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, consectetur?
          </p>
        </div>
    </div>
      )
 }

export default function Home() {
  const [searchInput, setSearchInput] = useState('')
  const onChangeValue = (e) => {
      setSearchInput(e.target.value)
  }
 
  return (
    <>
      <Head>
        <title>Mainpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.introWrapper}>
        <div className={styles.introduction}>
          <h1 className={styles.title}>Convenient shopping experience for everyone</h1>
          <p> 
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ut temporibus magnam labore deserunt iure nostrum earum unde magni dignissimos officiis.
          </p>
          <div className={styles.inputWrapper}>
            <label className={styles.searchInput}>
              <input type={'text'} onChange={onChangeValue}/>
               </label>
            <div className={styles.searchBtn}>Find</div>
          </div>
      </div>
        <img src='/market.jpg' className={styles.decoPic}/>
        </div>
        <div className={styles.recBox}>
        <div className={styles.recomContainer}>
          <div className={styles.recomTitle}>
            <h3>With us</h3>
          </div>
        <div className={styles.itemContainer}>
          <Card title={'Convenient'}/>
          <Card title={'Convenient'}/>
          <Card title={'Convenient'}/>
          <Card title={'Convenient'}/>

        </div>
 
        </div>
        </div>

     </main>
    </>
  )
}
